#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 A S Lewis
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.


"""Gymbob main file."""


# Import Gtk modules
#   ...


# Import other modules
import os
import sys
import importlib.util


# Add module directory to path to prevent import issues
spec = importlib.util.find_spec('gymbob')
if spec is not None:
    sys.path.append(os.path.abspath(os.path.dirname(spec.origin)))
    

# Import our modules
import mainapp


# 'Global' variables
__packagename__ = 'gymbob'
__prettyname__ = 'GymBob'
__version__ = '1.002'
__date__ = '28 Mar 2020'
__copyright__ = 'Copyright \xa9 2020 A S Lewis'
__license__ = """
Copyright \xa9 2020 A S Lewis.

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <http://www.gnu.org/licenses/>.
"""
__author_list__ = [
    'A S Lewis',
]
__description__ = 'Simple script to prompt the user during a workout'
__website__ = 'http://gymbob.sourceforge.io'
__app_id__ = 'io.sourceforge.gymbob'


# Start Gymbob
app = mainapp.GymBobApp()
app.run(sys.argv)
