.TH man 1 "28 Mar 2020" "1.002" "gymbob man page"
.SH NAME
gymbob \- simple script to prompt the user during a workout
.SH SYNOPSIS
gymbob
.SH DESCRIPTION
Designed for use at the gym, GymBob prompts the user (graphically and using
sound effects) at regular intervals during a workout. The workout programmes
are completely customistable. GymBob is written in Python 3 / Gtk 3 and runs
on Linux/*BSD.
.SH OPTIONS
The gymbob executable does not take any options.
.SH BUGS
No known bugs.
.SH AUTHOR
A S Lewis (aslewis@cpan.org)
