.TH man 1 "8 Aug 2021" "2.3.332" "tartube man page"
.SH NAME
tartube \- GUI front-end for youtube-dl
.SH SYNOPSIS
tartube
.SH DESCRIPTION
Tartube is a GUI front-end for youtube-dl, partly based on youtube-dl-gui and
written in Python 3 / Gtk 3. It's a convenient way to download videos from
YouTube and hundreds of other sites (or just to fetch a list of those videos,
if you prefer).
.SH OPTIONS
The tartube executable does not take any options.
.SH SEE ALSO
youtube-dl(8)
.SH BUGS
No known bugs.
.SH AUTHOR
A S Lewis (aslewis@cpan.org)
